build:
  maxIssues: 30
  weights:
    LongParameterList: 0
    comments: 0
complexity:
  ComplexCondition:
    threshold: 5
  TooManyFunctions:
    ignorePrivate: true
    thresholdInFiles: 20
  LongParameterList:
    active: false
exceptions:
  TooGenericExceptionCaught:
    active: false
style:
  ThrowsCount:
    max: 5
    excludeGuardClauses: true
  ReturnCount:
    max: 5
    excludeGuardClauses: true
  ForbiddenComment:
    active: false # allow usage of "TODO" comments
  MaxLineLength:
    excludes: ['**/test/**']
    active: true
    maxLineLength: 120
    excludePackageStatements: true
    excludeImportStatements: true
    excludeCommentStatements: false
    excludeRawStrings: true
  MagicNumber:
    ignorePropertyDeclaration: true
    ignoreAnnotation: true
    ignoreEnums: true
    ignoreRanges: true
#    active: false
