name: Build & Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    container:
      image: eclipse-temurin:17.0.18_8-jdk-alpine-3.23

    steps:
      - uses: actions/checkout@v4

      - name: Gradle
        run: ./gradlew check --no-daemon
