name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: eclipse-temurin:17.0.18_8-jdk-alpine-3.23

    steps:
      - uses: actions/checkout@v4

      - name: Gradle build
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}
          GPG_PASS: ${{ secrets.GPG_PASS }}
          PUBLISH_USER: ${{ secrets.PUBLISH_USER }}
          PUBLISH_PASS: ${{ secrets.PUBLISH_PASS }}
        run: |
          VERSION=${{ github.ref_name }}
          VERSION=${VERSION#v}
          export VERSION
          echo "Publish $VERSION"
          ./gradlew lintKotlin check jacocoTestReport publishAggregationToCentralPortal --no-daemon

      - name: Codecov - Install dependencies
        run: |
          apk add --no-cache bash git curl

      - name: Codecov - Upload
        uses: codecov/codecov-action@v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
