name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-22.04
    container:
      image: eclipse-temurin:17.0.18_8-jdk-alpine-3.23

    steps:
      - uses: actions/checkout@v4

      - name: Gradle build
        run: |
          VERSION=${{ github.ref_name }}
          VERSION=${VERSION#v}
          export VERSION
          echo "Publish $VERSION"
          ./gradlew lintKotlin check codeCoverageReport publishAggregationToCentralPortal --no-daemon

      - name: Codecov
        uses: codecov/codecov-action@v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
